//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Shopping_AppEntities : DbContext
    {
        public Shopping_AppEntities()
            : base("name=Shopping_AppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Retailer> Retailers { get; set; }
        public virtual DbSet<Update_Products> Update_Products { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
    
        public virtual ObjectResult<Retailer_Revenue_Result> Retailer_Revenue(Nullable<int> retail_Id)
        {
            var retail_IdParameter = retail_Id.HasValue ?
                new ObjectParameter("Retail_Id", retail_Id) :
                new ObjectParameter("Retail_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Retailer_Revenue_Result>("Retailer_Revenue", retail_IdParameter);
        }
    
        public virtual ObjectResult<Retailer_Revenues_Result> Retailer_Revenues(string retail_Name)
        {
            var retail_NameParameter = retail_Name != null ?
                new ObjectParameter("Retail_Name", retail_Name) :
                new ObjectParameter("Retail_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Retailer_Revenues_Result>("Retailer_Revenues", retail_NameParameter);
        }
    
        public virtual ObjectResult<retailer_revdetails_Result> retailer_revdetails(Nullable<int> retail_id)
        {
            var retail_idParameter = retail_id.HasValue ?
                new ObjectParameter("retail_id", retail_id) :
                new ObjectParameter("retail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<retailer_revdetails_Result>("retailer_revdetails", retail_idParameter);
        }
    
      
    }
}
